FROM node:18-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@8.6.12 --activate

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY prisma ./prisma
RUN pnpm prisma generate

EXPOSE 3000

CMD ["pnpm", "dev"]
