name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: proposal
    attributes:
      label: What's your idea?
      description: Describe what you want to add or improve.
      placeholder: I think we should...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this needed?
      description: Explain the problem it solves or value it adds.
      placeholder: This feature would help because...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: false
